# Generated by Django 5.0.6 on 2024-05-13 14:59

from django.db import migrations

def ostap_debil(apps, schema_editor):
    Article = apps.get_model("mainPage", "Article")

    zalupa = Article.objects.filter(title="обриганський ніж").first()

    if zalupa:
        zalupa.delete()




class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [migrations.RunPython(ostap_debil)]
